spring:
  application:
    name: lslb-cms
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  sendgrid:
    api-key: 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

management:
  endpoint:
  enabled-by-default: false
  shutdown:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
  enabled-by-default: true
  health:
    show-details: ALWAYS
  shutdown:
    enabled: true

server:
  port: 2001 #${APPLICATIONPORT:2001}cld

security:
  enable-csrf: false
  ignored: /resources/**
  basic:
    enabled: false

#Pointing to Test Environment
mongodb:
  #hosts: db2.mlnx.test.vggdev.com:27017 #172.31.31.29:27017,172.31.22.131:27017
  #username: useradmin
  #password: f1nat3ch
  #database: LslbCMSDb
  hosts: 127.0.0.1
  username: cmsadmin
  password: finat3ch
  database: LslbCMSDb
  authDb:   LslbCMSDb
  replicaSet:

logging:
  level:
    ROOT: INFO

#Rememeber to change the credentials for SSO
sso:
  baseIdentityURL: https://sso.test.vggdev.com/identity
  baseAPIURL: http://ssoapi.test.vggdev.com
  apiUsername: lslb-cms-api
  apiPassword: fhhsnns___===i1omnsnaa
  clientId: lslb-cms
  clientSecret:  fhhsnns___===i1omnsnaa
  baseLogoutURL: https://sso.test.vggdev.com
  publicKeyURL: https://sso.test.vggdev.com/identity/.well-known/jwks
  applicationName: lslb-cms

jwt:
  header: Authorization

#Web Interface Client
racs:
  ui:
    host: localhost
    port: 3000

#Vigipay Integration
vigipay:
  client_id: LAGOS_STATE_LOTTERIES_BOARD_API1G302IAOYGB6
  client-secret: pgmDKCCqeXfb3eXK
  username: tunde123@mailinator.com
  password: Password@12
  scope: ebipsgatewayapi offline_access roles profile
  grant-type: password
  token-url: http://sso.test.vggdev.com/identity/connect/token
  loop-base-url: https://ebipsgateway.test.vggdev.com/api
  country-code: 566
  location-code: LOC
  currency-code: NGN
  corporate-revenue-code: Default
  corporate-code: COR4U7CJTRAZW7H

#SMTP Integration
email-host: email-smtp.eu-west-1.amazonaws.com
email-username: AKIA4NIIUUQEN2XFDDOZ #support@lslbcms.com
email-password: BBy0JX5u+q/jfx3XvLcbfC+kxPp0rc4Hub/lMwbCeEzl #At16c00DP+uonPCk6KuuGeaHNM3NzfF/Ga6VFGcmuR5d #BBy0JX5u+q/jfx3XvLcbfC+kxPp0rc4Hub/lMwbCeEzl
email-port: 587

#Amazon Integration
amazon:
  s3:
    bucket-name: vgg-aws-finatech
    access-key-id: AKIA4NIIUUQEO26RTVXY
    secret-access-key: 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

seed_user_1:
  email: oladapo.animashaun@venturegardengroup.com #seed_user1_email:oladapo.animashaun@venturegardengroup.com
