spring:
  application:
    name: lslb-cms-user-service
  #jackson:
    #time-zone: GMT
management:
  endpoint:
  enabled-by-default: false
  shutdown:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
  enabled-by-default: true
  health:
    show-details: ALWAYS
  shutdown:
    enabled: true
eureka:
  instance:
    #hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/
server:
  port: ${APPLICATIONPORT:2002}
security:
  enable-csrf: false
  ignored: /resources/**
  basic:
    enabled: false
mongodb:
  host: localhost
  username:
  password: 
  database: LslbCmsUserDB
  port: 27017
logging:
  level:
    ROOT: INFO
    #Rememeber to change the credentials for SSO
sso:
  baseIdentityURL: https://sso.test.vggdev.com/identity
  baseAPIURL: http://ssoapi.test.vggdev.com
  apiUsername: lslb-cms-api
  apiPassword: fhhsnns___===i1omnsnaa
  clientId: lslb-cms
  clientSecret:  fhhsnns___===i1omnsnaa
  baseLogoutURL: https://sso.test.vggdev.com
  publicKeyURL: https://sso.test.vggdev.com/identity/.well-known/jwks
  applicationName: lslb-cms

jwt:
  header: Authorization


racs:
  ui:
    host: localhost
    port: 3000

    
email-host: smtp.gmail.com
email-username: lslbcms@gmail.com
email-password: password@123456
email-port: 587