spring:
  application:
    name: lslb-cms
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
management:
  endpoint:
  enabled-by-default: false
  shutdown:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
  enabled-by-default: true
  health:
    show-details: ALWAYS
  shutdown:
    enabled: true
server:
  port: ${APPLICATIONPORT:2001}
security:
  enable-csrf: false
  ignored: /resources/**
  basic:
    enabled: false
mongodb:
  hosts: db2.mlnx.staging.vggdev.com:27017 #172.31.31.29:27017,172.31.22.131:27017
  username: useradmin
  password: f1nat3ch-user
  database: LslbCMSDb
  authDb: admin
  replicaSet:


logging:
  level:
    ROOT: INFO
    #Rememeber to change the credentials for SSO





sso:
  baseIdentityURL: https://sso.staging.vggdev.com/identity
  baseAPIURL: http://ssoapi.staging.vggdev.com
  apiUsername: lslb-cms-api
  apiPassword: fhhsnns___===i1omnsnaa
  clientId: lslb-cms
  clientSecret:  fhhsnns___===i1omnsnaa
  baseLogoutURL: https://sso.staging.vggdev.com
  publicKeyURL: https://sso.staging.vggdev.com/identity/.well-known/jwks
  applicationName: lslb-cms

jwt:
  header: Authorization


racs:
  ui:
    host: lslbcms.staging.vggdev.com
    port:


vigipay:
  client_id: LAGOS_STATE_LOTTERIES_BOARD_API1DHHBDDWJ1MT
  client-secret: EybYKnXXRQv4LiNE
  username: adeboludeyi@gmail.com
  password: vigipayP@ssw0rd
  scope: ebipsgatewayapi offline_access roles profile
  grant-type: password
  token-url: https://ebipssso.staging.vggdev.com/core/connect/token
  loop-base-url: https://ebipsgateway.staging.vggdev.com/api
  country-code: 566
  location-code: LOC
  currency-code: NGN
  corporate-revenue-code: 12345


email-host: smtp.gmail.com
email-username: lslbcms@gmail.com
email-password: password@123456
email-port: 587

